When I try to compile the following code with Scala 2.8.0.r16921-b20090115021734

{code}
def x = synchronized { throw new Exception }
{code}

I get a dead code warning

{code}
(fragment of unreachable.scala):1: warning: dead code following this construct
def x = synchronized { throw new Exception }
                        ^
{code}

No code follows the {{throw}}, so I think the warning is spurious. Perhaps {{synchronized}} generates some code which triggers the warning?
