This bug was reproduced under scala 2.8.0.r18462-b20090811081019 and 2.7.5. Most likely it can also manifest itself under 2.7.x and 2.8.

The code that reproduces it is:

scala> class Parameter {
    def this(value:Double) = {
        this()
    }

    def this(p:String) = {
        this(try{
                java.lang.Double.parseDouble( p )
            } catch {
                case _ => null.asInstanceOf[Double]
            }
        )
    }
}

scala> new Parameter("10.1")

After experimenting with changes in the code I determined that the following conditions are required to reproduce the bug:
 - There has to be a class with two constructors of different types (the number of arguments doesn't have to be the same even).
 - one constructor must call the other
 - the calling of the second of the second constructor inside the first has to have a try... catch block in the parameter (an if block does not work).

Apparently, the compiler does not acknowledge the the try ... catch
block has a 'Double' type and then calls the wrong constructor.

The following stack trace can be obtained from running the maven project attached to this bug report with the command 'mvn test'

-------------------------------------------------------------------------------
Test set: pt.cnbc.wikimodels.dataModel.SBMLModelTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.068 sec <<< FAILURE!
createModelWithParameters(pt.cnbc.wikimodels.dataModel.SBMLModelTest)  Time elapsed: 0.014 sec  <<< ERROR!
java.lang.VerifyError: (class: pt/cnbc/wikimodels/dataModel/Parameter, method: <init> signature: (Ljava/lang/String;)V) Expecting to find object/array on stack
        at pt.cnbc.wikimodels.dataModel.SBMLModelTest.createModelWithParameters(SBMLModelTest.scala:19)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.junit.runners.model.FrameworkMethod$$1.runReflectiveCall(FrameworkMethod.java:44)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:44)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:180)
        at org.junit.runners.ParentRunner.access$$000(ParentRunner.java:41)
        at org.junit.runners.ParentRunner$$1.evaluate(ParentRunner.java:173)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:220)
        at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:62)
        at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:140)
        at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:127)
        at org.apache.maven.surefire.Surefire.run(Surefire.java:177)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:338)
        at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:997)
This is a duplicate of #1909.  I'll add a pointer from there to here to make sure this case is also considered.
