The following code should print out "1" but instead
{code}
class Foo {
  private val x = 0
}
object test extends Application {
  val x = 1;
  {
    val f = new Foo
    import f._
    println(x)
  }
}
{code}
produces the error
{code}
test.scala:9: error: reference to x is ambiguous;
it is both defined in object test and imported subsequently by
import f._
    println(x)
            ^
one error found
{code}
both with Scala 2.7.5 and trunk. The `import f._` statement should not see the private member `x` in class `Foo`.


Weird, I just logged in to report this same bug.  How could it exist for so long and then be reported by two people on the same day, I don't know.

It's even more problematic than illustrated above.  Here is how I ran into it:
{code}
trait Foo {
  object bar {
    private[this] def fn() = 5
  }
}

trait Foo2 {
  object bip {
    def fn() = 10
  }
}

class Bob extends AnyRef with Foo with Foo2 {
  import bip._
  import bar._
  
  def go() = fn()
}

// a.scala:17: error: reference to fn is ambiguous;
// it is imported twice in the same scope by
// import bar._
// and import bip._
//   def go() = fn()
//              ^
{code}
It fails no matter what visibility restrictions one places on it - private, private[foo], private[this].
Paul's variant compiles now. Stephane's original example is not covered by the spec, which says that all importable members are counted. A member is importable as long as it is not private[this]. Why this wording? Because an inner class might validly
import the private members of its companion object.

The spec should only allow private members to be imported when it makes sense - i.e., when they are accessible.
I've hit the following variant of this bug:
{code}
scala> object Foo {
     | private def println(x: Any) {}
     | }
defined module Foo

scala> import Foo._
import Foo._

scala> println(1)
<console>:12: error: method println in object Foo cannot be accessed in object Foo
              println(1)
              ^
{code}

Getting compile errors from private members violates the principle of encapsulation: adding a private member to a class cannot be allowed to affect code where that member is not accessible.
This drives me nuts.  I can't believe adding a private method to a class can break a bunch of unrelated files which happen to reference the name.  It's not theoretical, it has happened to me several times.

another example that fails in 2.10, works in 2.11+

{code}
object Foo {
  def s = "foo"
}
object Bar {
  private def s = "bar"
}
object Test {
  import Foo._
  import Bar._
  println(s)
}
{code}
