{code}
object Fail {
  def nom (guard : => Boolean) (something : => Unit) { }
  def main(args: Array[String]) {
    nom {
      val i = 0
      (i != 3)
    }()
  }
}
{code}

On compilation of the program above, the Scala compiler spews a large backtrace starting with:
java.lang.Error: symbol value i$1 does not exist in $line1.$read$$iw$$iw$Fail.main
        at scala.tools.nsc.symtab.SymbolTable.abort(SymbolTable.scala:34)
        at scala.tools.nsc.backend.icode.GenICode$ICodePhase.scala$tools$nsc$backend$icode$GenICode$ICodePhase$$genLoad(GenICode.scala:1027)

full log is attached.


(I have no idea if this is a valid Scala program.  I am very new to the language.)

Replacing the last brackets () at the end of the `nom' call with {} brackets lets the program compile fine.

If the second lambda type is removed from nom's type and the () brackets removed from the nom call, the program also compiles fine.

my best guess is that the CBN transform messes up the symbol-owner structure of the block passed to nom as the first argument

it's weird that the second argument list is required to trigger this

simplified (attached):
{code}
object Test extends App {
  def nom (guard: => /*<-- must be CBN */Unit) (something: Unit) { }

  nom {
    val i = 0
    println(i) // i must be referenced
  }(/*must be omitted: ()*/)
}
{code}
{{nom(<expr>)()}} fails to typecheck, because the () is first interpreted as an empty argument list. But in the process of determining this, {{<expr>}} is wrapped in a {{Function0}}, and the symbols within have there owner changed. That {{Function0}} is discarded and things are tried again with a single Unit argument, but by this stage the ownership chain is messed up, and later attempts to patch the owner in {{Uncurry}} are impeded.
This was fixed in 2.10.4 under SI-8111. I've submitted the example given here as an extra test case : https://github.com/scala/scala/pull/4116
