Trying to compile the following code using scala2.11.2 and scalatest-2.2.1 gives me the attached error stacktrace. (Same behaviour in scala-2.10.4 and scalatest-2.2.0). Everything works as expected after either
- extracting the "new FakeLocalDate" to a val,
- or taking out "with DiagrammedAssertions".

{code}
class PossibleScalacBug extends FunSpec with DiagrammedAssertions {
  it("returns 42 as the total count") {
    assert(StubRepository.totalCountFor(new FakeLocalDate(2014, 8, 8)) == 42)
  }
}

object StubRepository {
  def totalCountFor(unusedDate: FakeLocalDate): Int = 42
}

class FakeLocalDate(year: Int, month: Int, day: Int)
{code}
This looks like a bug in Scalatest's assert macro.

/cc [~cheeseng]

Here's a minimal reproduction:

{noformat}
% tail build.sbt test.scala
==> build.sbt <==
scalaVersion := "2.11.2"

libraryDependencies += "org.scalatest" %% "scalatest" % "2.2.1"

==> test.scala <==
import org.scalatest._

class PossibleScalacBug {
  import DiagrammedAssertions._
  assert(new Object() == "")
}

% sbt compile
[info] Loading global plugins from /Users/jason/.sbt/0.13/plugins
[info] Loading project definition from /Users/jason/code/scratch3/project
[info] Set current project to scratch3 (in build file:/Users/jason/code/scratch3/)
[info] Compiling 1 Scala source to /Users/jason/code/scratch3/target/scala-2.11/classes...
[error]
[error]   Unexpected New(TypeTree(class Object)/Object) received in icode.
[error]   Call was genLoad(new Object,package <empty> { class PossibleScalacBug { def PossibleScalacBug.<init> { bb=1 } } },REF(class Object))
[error]      while compiling: /Users/jason/code/scratch3/test.scala
[error]         during phase: icode
...
{noformat}
