```scala
package foo

case class A(var a: Int)
object Test {
  val as = Map[String, A]()
  as(undefined).a += 1
}
```

Crashes the type checker with

```scala
scala.reflect.internal.FatalError: 
  symbol value <error> does not exist in foo.Test.<init>
     while compiling: /home/crc/transcriptic/src/lab/src/mcx/src/main/scala/com/transcriptic/mcx/devices/validation/Foo.scala
        during phase: icode
     library version: version 2.11.5
    compiler version: version 2.11.5
```
Running under -Xprint:typer points towards https://github.com/scala/scala/blob/2.11.x/src/compiler/scala/tools/nsc/typechecker/Typers.scala#L4617

It looks like the error in the RHS of the val (`qualqual`) is masked by evalOnce's wrapping?
```scala
      <synthetic> val ev$1: A = Test.this.as.apply(<undefined: error>);
      ev$1.a_=(ev$1.a.+(1))
```
When running under -Ytyper-debug, this looks dubious -- an application to an error-typed arg should be error-typed:

```scala
|    |    |    |-- as(<undefined: error>).a EXPRmode-POLYmode-QUALmode (site: method test in Test) 
|    |    |    |    |-- String => A EXPRmode-POLYmode-QUALmode (site: method test in Test) 
|    |    |    |    |    |-- as.apply BYVALmode-EXPRmode-FUNmode-POLYmode (silent: method test in Test) 
|    |    |    |    |    |    \-> (v1: String)A
|    |    |    |    |    \-> A
|    |    |    |    \-> Int
```
I think this is duplicate with #9781. The example results in `error: not found: value undefined` instead of compiler crash on 2.12.x.
